In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

def split_dataset(data, labels, split_ratio=0.2, seed=None):
    first_set, second_set, first_labels, second_labels = train_test_split(
        data, labels, test_size=split_ratio, stratify=labels, random_state=seed
    )

    return first_set, second_set, first_labels, second_labels




data_points = np.array([
    [2.1, 3.4], [1.3, 2.9], [3.6, 4.1], [2.2, 3.1], [1.7, 2.6],
    [3.2, 3.9], [4.7, 5.3], [3.9, 4.6], [2.5, 3.2], [1.9, 2.8],
    [3.4, 4.0], [2.0, 3.5], [4.2, 4.8], [1.8, 2.7], [3.1, 3.7]
])


class_labels = np.array([0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

train_set, test_set, train_labels, test_labels = split_dataset(data_points, class_labels, split_ratio=0.3, seed=7)


print("TRAINING DATA:\n", train_set)
print()
print("LABELS OF TRAINING DATA:\n", train_labels)
print()
print("TESTING DATA:\n", test_set)
print()
print("LABELS OF TESTING DATA:\n", test_labels)


TRAINING DATA:
 [[3.4 4. ]
 [4.2 4.8]
 [2.1 3.4]
 [1.9 2.8]
 [2.2 3.1]
 [3.2 3.9]
 [4.7 5.3]
 [2.  3.5]
 [2.5 3.2]
 [1.7 2.6]]

LABELS OF TRAINING DATA:
 [0 0 0 1 1 0 0 1 1 1]

TESTING DATA:
 [[3.1 3.7]
 [3.9 4.6]
 [1.8 2.7]
 [3.6 4.1]
 [1.3 2.9]]

LABELS OF TESTING DATA:
 [0 0 1 0 1]
